project: 
  type: book

book: 
  page-navigation: true
  title: "Ait cookbook" 
  site-url: "https://w1996jy.github.io/Aitcookbook" 
  repo-url: "https://github.com/w1996jy/Aitcookbook"
  repo-actions: [edit, source, issue]
  favicon: assets/favicon.ico
  downloads: [pdf, docx]
  search: true
  
  author:
    - name: Junyue Wang
      affiliations:
        - name: Shandong Agricultural University
          department: State Key Laboratory of Crop Biology, College of Agronomic Sciences
    - name: Fei Liang
      institute: test
      affiliations:
        - name: Henan University
          department: State Key Laboratory of Crop Stress Adaptation and Improvement
    - name: M. Waqar Khan
      affiliations:
        - name: Henan University
          department: SState Key Laboratory of Crop Stress Adaptation and Improvement
  
  chapters:
    - index.qmd
    - content/introduce.qmd
    - content/installation.qmd
    - content/analyse/analyse.qmd
    chapters:
      - content/analyse/Merge_File.qmd
      - content/analyse/Correlation_Analysis.qmd
      - content/analyse/Descriptive_Statistics.qmd
      - content/analyse/DESeq2.qmd
    chapters:
      - content/plot/plot.qmd
      - content/plot/Bar.qmd
      - content/plot/Venn.qmd
      - content/plot/Enrichment_Bubble.qmd
      - content/plot/Volcano_Plot.qmd
      - content/plot/Wordcloud_Plot.qmd
      - content/plot/Histogram.qmd
      - content/plot/PCA.qmd

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#FCD581"
    logo: "https://github.com/w1996jy/Aitcookbook/blob/main/assets/logo.png?raw=true"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://w1996jy.github.io
        text: "Open Science"
    style: "docked"
    search: true
    collapse-level: 1

execute:
  echo: false
  code-overflow: wrap

format:
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"
    keep-tex: true
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: [cosmo, assets/theme.scss] 
    toc: true
    toc-depth: 3

filters:
  - assets/include-files.lua
  - quarto

# Comment next 2 lines if the PDF is having trouble
metadata-files:
  - _frontmatter.yml
 
